"""Add report_times table

Revision ID: 4c5db24d2e06
Revises: 
Create Date: 2025-12-01 14:41:03.821593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5db24d2e06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_times',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_times_report_id'), 'report_times', ['report_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_states',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'failed', 'completed', 'running_agents', 'agents_completed', 'agents_failed', 'agents_partial_success', 'generating_nlg', 'nlg_completed', 'generating_summary', 'summary_completed', name='reportstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('partial_agent_output', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('final_report_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_states_status'), 'report_states', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_states_status'), table_name='report_states')
    op.drop_table('report_states')
    op.drop_table('reports')
    op.drop_index(op.f('ix_report_times_report_id'), table_name='report_times')
    op.drop_table('report_times')
    # ### end Alembic commands ###
